#!/bin/bash
# This script is designed to automatically refactor the entire codebase to use the new,
# namespaced localization keys generated by the `slang` tool.

# CRITICAL ASSUMPTION: This script operates on the assumption that, before the introduction of
# namespaces, every translation key was unique across all .arb files. If the same key
# (e.g., "name") existed in multiple files, this script cannot resolve that ambiguity
# and may assign an incorrect namespace.

set -e # Exit immediately if any command fails.

echo "--- Starting Comprehensive Localization Refactoring ---"

# Step 1: Correct all localization import statements across the project.
echo "[1/3] Updating import statements to use 'translations.g.dart'..."
find lib test -type f -name "*.dart" -print0 | xargs -0 sed -i 's|package:muhaseb_pro/l10n/app_localizations.dart|package:muhaseb_pro/l10n/translations.g.dart|g'
find lib test -type f -name "*.dart" -print0 | xargs -0 sed -i 's|l10n/app_localizations.dart|l10n/translations.g.dart|g'
echo "Import statements updated successfully."

# Step 2: Analyze all .arb files and generate a master script of refactoring commands.
# This approach is robust, as it builds all commands first before executing them.
echo "[2/3] Analyzing .arb files and preparing refactoring plan..."
TEMP_SED_SCRIPT=$(mktemp)
# Ensure cleanup of the temporary file on script exit
trap 'rm -f "$TEMP_SED_SCRIPT"' EXIT

ARB_FILES=$(find lib/l10n/en -name "*.arb")

for arb_file in $ARB_FILES; do
    # Determine the full namespace from the file path.
    # e.g., 'lib/l10n/en/gl/reports.arb' becomes 'gl.reports'
    namespace_path=$(dirname "${arb_file#lib/l10n/en/}")
    namespace_base=$(basename "$arb_file" .arb)

    if [ "$namespace_path" == "." ]; then
        namespace="$namespace_base"
    else
        # The sed command removes a potential leading './' from the path
        namespace=$(echo "$namespace_path/$namespace_base" | sed 's/^\.\///')
    fi
    # Replace slashes with dots for valid Dart syntax, e.g., 'gl/reports' -> 'gl.reports'
    namespace=${namespace//\//.}

    # Extract every key from the current .arb file using jq.
    # The `select` clause filters out metadata keys that start with '@'.
    keys=$(jq -r 'keys_unsorted[] | select(startswith("@") | not)' "$arb_file")

    for key in $keys; do
        # Generate a highly specific sed command for this key and append it to our master script.
        # The regex `\bt\.$key\b` uses word boundaries (\b) to ensure it only matches
        # the exact key (e.g., `t.login`) and not partials (e.g., `t.loginButton` or `my_t.login`).
        # This is the key to preventing incorrect replacements.
        echo "s/\bt\.$key\b/t.$namespace.$key/g" >> "$TEMP_SED_SCRIPT"
    done
done
echo "Refactoring plan generated."

# Step 3: Execute the master refactoring script against all Dart files in the project.
echo "[3/3] Applying all refactoring commands to lib/ and test/ directories..."
# This command applies the entire set of sed rules to each file at once, which is highly efficient.
find lib test -type f -name "*.dart" -print0 | xargs -0 sed -i -f "$TEMP_SED_SCRIPT"
echo "Refactoring applied successfully."

echo "--- Localization Refactoring Complete ---"
echo "Running 'flutter analyze' to verify the results and identify any remaining issues."
flutter analyze
