enum AppPermission {
  // System Setup Permissions
  viewSystemSetup,
  manageCompanyInfo,
  viewBranches,
  manageChartOfAccounts,
  viewUsers,
  manageUsers,
  viewRoles,
  manageRoles,
  managePermissions,

  // General Ledger Permissions
  viewGeneralLedger,
  manageGLSetup,
  viewGLSetup,
  viewJournalVouchers,
  createJournalVouchers,
  editJournalVouchers,
  deleteJournalVouchers,
  postJournalVouchers,
  reverseJournalVouchers,
  viewPaymentVouchers,
  createPaymentVouchers,
  editPaymentVouchers,
  deletePaymentVouchers,
  postPaymentVouchers,
  reversePaymentVouchers,
  viewReceiptVouchers,
  createReceiptVouchers,
  editReceiptVouchers,
  deleteReceiptVouchers,
  postReceiptVouchers,
  reverseReceiptVouchers,

  // Inventory Permissions
  viewInventory,
  manageInventorySetup,
  viewInventorySetup,
  manageItems,
  viewItems,
  createItems,
  editItems,
  deleteItems,
  manageWarehouses,
  viewWarehouses,
  createWarehouses,
  editWarehouses,
  deleteWarehouses,
  manageItemGroups,
  viewItemGroups,
  createStockOperations,
  editStockOperations,
  postStockOperations,
  viewStockOperations,
  manageStocktaking,
  viewStocktaking,
  manageReservations,
  viewReservations,
  viewInventoryReports,
  // ... add all other permissions here as the app grows
}
