// Mocks generated by Mockito 5.4.6 from annotations
// in muhaseb_pro/test/features/system_setup/domain/usecases/financial_periods_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:muhaseb_pro/features/system_setup/domain/entities/financial_period_entity.dart'
    as _i6;
import 'package:muhaseb_pro/features/system_setup/domain/repositories/financial_periods_repository.dart'
    as _i3;
import 'package:muhaseb_pro/shared/domain/entities/failures.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FinancialPeriodsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinancialPeriodsRepository extends _i1.Mock
    implements _i3.FinancialPeriodsRepository {
  MockFinancialPeriodsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.FinancialPeriodEntity>>>
      getFinancialPeriods() => (super.noSuchMethod(
            Invocation.method(
              #getFinancialPeriods,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i6.FinancialPeriodEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.FinancialPeriodEntity>>(
              this,
              Invocation.method(
                #getFinancialPeriods,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.FinancialPeriodEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FinancialPeriodEntity>>
      getFinancialPeriodByCode(String? periodCode) => (super.noSuchMethod(
            Invocation.method(
              #getFinancialPeriodByCode,
              [periodCode],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.FinancialPeriodEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.FinancialPeriodEntity>(
              this,
              Invocation.method(
                #getFinancialPeriodByCode,
                [periodCode],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.FinancialPeriodEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addFinancialPeriod(
          _i6.FinancialPeriodEntity? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFinancialPeriod,
          [period],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addFinancialPeriod,
            [period],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateFinancialPeriod(
          _i6.FinancialPeriodEntity? period) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFinancialPeriod,
          [period],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateFinancialPeriod,
            [period],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> toggleLockFinancialPeriod(
    String? periodCode,
    bool? isLocked,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLockFinancialPeriod,
          [
            periodCode,
            isLocked,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #toggleLockFinancialPeriod,
            [
              periodCode,
              isLocked,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteFinancialPeriod(
          String? periodCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFinancialPeriod,
          [periodCode],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteFinancialPeriod,
            [periodCode],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
